name: Build
on:
  push:
    branches:
      - '*'
    tags-ignore:
      - 'v*'
  pull_request:

env:
  JAVA_VERSION: 17
  GRADLE_VERSION: 8.8

jobs:
  build:
    name: Build and Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Java ${{ env.JAVA_VERSION }}
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: ${{ env.JAVA_VERSION }}

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: ${{ env.GRADLE_VERSION }}
          dependency-graph: generate-and-submit

      - name: Build with Gradle
        run: ./gradlew build test --stacktrace --no-daemon

      - name: capture build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Artifacts
          path: '**/build/libs/*.jar'
