name: Release

on:
  release:
    types: [created]

permissions:
  contents: write
  pages: write
  id-token: write

env:
  JAVA_VERSION: 17
  GRADLE_VERSION: 8.8

jobs:
  publish:
    name: Build then JitPack
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Get the release version, removing the v from the tag
        id: get_version
        run: echo "RELEASE_VERSION=${GITHUB_REF/refs\/tags\/v/}" >> $GITHUB_OUTPUT

      - name: Request release from JitPack to trigger build
        run: |
          JITPACK_URL="https://jitpack.io/com/github/jimschubert/rewrite-docker/${{ steps.get_version.outputs.RELEASE_VERSION }}/"
          curl -X POST -s -m 30 ${JITPACK_URL} || true
